name: Workflow
on: [push, pull_request]
jobs:
  Test:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.3.0
      with:
        xcode-version: latest
    - name: Install Dependencies
      run: pod install --repo-update
      shell: bash
    - name: Test
      uses: ty0x2333/cocoapods-action@master
      with:
        additional_lint_params: --private
        workspace: MarvelApp.xcworkspace
        scheme: MarvelApp
        additional_build_params: -destination 'platform=iOS Simulator,id=2B687EA3-12C4-4E51-A7B6-FEEBE2F39915'
        lint: false
    - name: Upload codecoverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
#         files: ./coverage1.xml,./coverage2.xml # optional
#         flags: unittests # optional
#         name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
#         verbose: true # optional (default = false)
