name: Workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.3.0
      with:
        xcode-version: latest
    - name: Install Dependencies
      run: pod install --repo-update
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        additional_lint_params: --private
    - name: Run unit tests
      run: xcodebuild test -scheme MarvelApp -workspace MarvelApp.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.4' | xcpretty && exit ${PIPESTATUS[0]}
