name: Workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.3.0
      with:
        xcode-version: latest
    - name: Install Dependencies
      run: pod install --repo-update
      shell: bash
    - name: Test
      uses: ty0x2333/cocoapods-action@master
      with:
        additional_lint_params: --private
        workspace: MarvelApp.xcworkspace
        scheme: MarvelApp
        additional_build_params: -destination 'platform=iOS Simulator,id=761CB82C-2702-47C8-B912-02836EC02359'
        lint: false
